name: Learning
on:
  push:
    branches:
      - main
jobs:
  build:
    runs on: ubuntu-latest
    steps:
      - name: Pull code
        uses: actions/checkout@v4
      - name: Build using maven
        run: mvn install
      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: vprofile
          path: target/*.war  